site_name: Rained
plugins: []
nav:
  - Home: index.md
  - Manual:
    - Brief: brief.md
    - User interface: user-interface.md
    - Editing the level:
      - Overview: level-view.md
      - Environment: editors/env.md
      - Geometry: geometry.md
      - Tiles: tiles.md
      - Cameras: cameras.md
      - Light: light.md
      - Effects: effects.md
      - Props: props.md
    - Further reading: resources.md
theme:
  name: readthedocs
markdown_extensions:
  - def_list
  - attr_list

site_url: ""
use_directory_urls: False