# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Nightly build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install MkDocs
        run: pip install mkdocs-material
      - name: MkDocs build
        run: mkdocs build
      - name: Upload documentation site
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: ./dist/docs
  
  linux-package:
    runs-on: ubuntu-latest
    needs: [build-docs]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: |
        cd src/Drizzle
        dotnet run --project Drizzle.Transpiler
        cd ../..
        dotnet restore
    - name: Get documentation build
      uses: actions/download-artifact@v4
      with:
        name: docs
        path: ./dist
    - name: Restore Cake Tool
      run: dotnet tool restore
    - name: Linux Package
      run: dotnet cake --os=linux-x64 --target=Package
    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-x64
        path: ./rained_linux-x64.tar.gz
  
  windows-package:
    runs-on: ubuntu-latest
    needs: [build-docs]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: |
        cd src/Drizzle
        dotnet run --project Drizzle.Transpiler
        cd ../..
        dotnet restore
    - name: Get documentation build
      uses: actions/download-artifact@v4
      with:
        name: docs
        path: ./dist
    - name: Restore Cake Tool
      run: dotnet tool restore
    - name: Windows Package
      run: dotnet cake --os=win-x64 --target=Package
    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4
      with:
        name: win-x64
        path: ./rained_win-x64.zip

  create_release:
    needs: [windows-package, linux-package]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Download Linux Artifact
      uses: actions/download-artifact@v4
      with:
        name: linux-x64
        path: ./artifacts/
    - name: Download Windows Artifact
      uses: actions/download-artifact@v4
      with:
        name: win-x64
        path: ./artifacts/
    - name: Remove Old Release
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh release delete nightly --cleanup-tag -y
    - name: Create Release
      uses: softprops/action-gh-release@v2
      id: create_release
      with:
        draft: false
        prerelease: true
        name: "Nightly"
        tag_name: "nightly"
        make_latest: false
        body: Latest in-development build.
        files: |
          ./artifacts/rained_linux-x64.tar.gz
          ./artifacts/rained_win-x64.zip